In [1]:
import numpy as np
from llm_architect import positionEncoding

In [2]:
T = 4
d_model = 6

In [5]:
pe = positionEncoding(T, d_model=d_model)

In [6]:
pe.shape

(4, 6)

In [7]:
pe[0]

array([0., 1., 0., 1., 0., 1.])

In [8]:
pe[1]

array([8.41470985e-01, 9.98922976e-01, 2.15443302e-03, 9.99999995e-01,
       4.64158883e-06, 1.00000000e+00])

In [9]:
rng = np.random.default_rng(3000)

In [10]:
embeddingResult = rng.random((3, T, d_model), dtype = np.float64)

In [11]:
embeddingResult + pe[None, :, :]

array([[[0.43651544, 1.32807961, 0.42113886, 1.19423973, 0.27924363,
         1.17357217],
        [1.45629971, 1.88531036, 0.7813586 , 1.4337933 , 0.29928337,
         1.82881046],
        [0.95857344, 1.02213169, 0.11558577, 1.96815617, 0.03143549,
         1.7505235 ],
        [1.08167238, 1.49303306, 0.46906482, 1.26518587, 0.11553425,
         1.31200184]],

       [[0.04423484, 1.35513565, 0.8834744 , 1.13887997, 0.72389692,
         1.00325498],
        [1.15055757, 1.05528248, 0.5628456 , 1.77438638, 0.86843137,
         1.45597669],
        [1.0645602 , 1.3924645 , 0.80362648, 1.40633793, 0.24590708,
         1.86487483],
        [1.01789323, 1.16059077, 0.64666372, 1.60612867, 0.23566077,
         1.85620383]],

       [[0.01809642, 1.12982817, 0.17986949, 1.25327646, 0.5981617 ,
         1.03892756],
        [1.32490911, 1.06712215, 0.89142849, 1.60962169, 0.52980644,
         1.78917929],
        [1.09488657, 1.27081265, 0.28621205, 1.2472787 , 0.86732234,
         1.410263