In [1]:
import numpy as np
from llm_operator import softmax, softmaxBackward
# from operator import softmax, softmaxBackward 

In [2]:
rng = np.random.default_rng(1000)

In [7]:
X = rng.random((2, 4, 6), np.float64)
print(X)

[[[0.54431565 0.37965069 0.60442473 0.73460399 0.98840812 0.89224091]
  [0.51964178 0.20820684 0.29894051 0.83552541 0.18450649 0.18375199]
  [0.23502814 0.65818858 0.51673102 0.82385723 0.18965801 0.98047955]
  [0.39284504 0.45345328 0.27428462 0.3227665  0.62741705 0.43136525]]

 [[0.07660225 0.09861362 0.06647744 0.7077515  0.90849204 0.40254213]
  [0.50306421 0.24188559 0.69874299 0.88569365 0.93542321 0.19316749]
  [0.95909555 0.67499364 0.74070019 0.43406363 0.61999626 0.52964891]
  [0.65987263 0.79797313 0.13226049 0.86629113 0.70724855 0.34756816]]]


In [8]:
dOut = rng.random(X.shape, np.float64)

In [5]:
output, cache = softmax(X)

In [6]:
output

array([[[0.18213829, 0.19779326, 0.1731784 , 0.13250607, 0.18348621,
         0.13089779],
        [0.11962692, 0.19181163, 0.15672678, 0.2141238 , 0.20198723,
         0.11572364],
        [0.11788253, 0.26081902, 0.19053356, 0.12905182, 0.11955116,
         0.1821619 ],
        [0.16317113, 0.2087219 , 0.22519327, 0.09909982, 0.17093519,
         0.1328787 ]],

       [[0.10401622, 0.13673689, 0.14964567, 0.14090157, 0.26232346,
         0.20637618],
        [0.13647286, 0.16781875, 0.26818313, 0.13812643, 0.12634309,
         0.16305574],
        [0.16725251, 0.24650097, 0.11092517, 0.17302429, 0.19210368,
         0.11019338],
        [0.12084098, 0.09468135, 0.15828333, 0.22981533, 0.18511766,
         0.21126135]]])

In [9]:
dX = softmaxBackward(dOut, cache)

In [11]:
dX.shape

(2, 4, 6)