In [38]:
import os
from config import CHECKPOINT_DIR
from pathlib import Path

from llm_operator import Relu, Relu_backward

from helper import getRootPath

### Trial

In [2]:
targetPath = os.path.join(CHECKPOINT_DIR, "testLoad.txt")
print(targetPath)

checkpoint\testLoad.txt


In [3]:
ROOT_DIR = Path.cwd()
print(ROOT_DIR)

d:\llm-scratch\notebooks


In [4]:
currentPath = str(ROOT_DIR)

In [5]:
projectPath = currentPath.find("llm-scratch")

In [6]:
currentPath[0: projectPath + len("llm-scratch")]

'd:\\llm-scratch'

In [7]:
getRootPath()

'd:\\llm-scratch'

### Try open and read file

D:\llm-scratch\checkpoint\testLoad.txt

In [8]:
filePath = os.path.join(getRootPath(), "checkpoint", "testLoad.txt")
print(filePath)
print("d:\\llm-scratch\\checkpoint\\testLoad.txt")
f = open(filePath, mode="r")

d:\llm-scratch\checkpoint\testLoad.txt
d:\llm-scratch\checkpoint\testLoad.txt


In [9]:
f = open("checkRead.txt", mode="r+")

### test attention

In [10]:
from transformer import Attention_init,Attention

In [11]:
B = 2
T = 4
d_model = 8

In [12]:
attentionInit = Attention_init.randomInitial(seeds=2000, d_model= d_model)

In [13]:
attention = Attention(attentionInit, name="testerAttention1")

In [14]:
attention.save_checkpoint()

Attention : testerAttention1, already save at the checkpoint @ d:\llm-scratch\checkpoint\testerAttention1.transformer.npz


In [15]:
copyingAttention = Attention.load_checkpoint(name="testerAttention1")

In [16]:
attention.Wk

array([[[0.36697658, 0.06369904, 0.11757953, 0.77782075, 0.49271612,
         0.26702898, 0.86802038, 0.69536612],
        [0.5710032 , 0.45574301, 0.30102574, 0.49330926, 0.15119503,
         0.57102484, 0.60463195, 0.33183582],
        [0.39867866, 0.2517794 , 0.65944202, 0.16160868, 0.15887035,
         0.08650789, 0.78103235, 0.84101309],
        [0.95848306, 0.92405462, 0.25148575, 0.43516406, 0.52300296,
         0.51775528, 0.75750532, 0.73836277],
        [0.03678485, 0.89462939, 0.45157634, 0.90545964, 0.41529144,
         0.25935511, 0.70386579, 0.34904258],
        [0.49665182, 0.81878398, 0.61515928, 0.21548799, 0.10016537,
         0.54760782, 0.35043095, 0.51290781],
        [0.62641349, 0.33198524, 0.04050908, 0.79537053, 0.1170476 ,
         0.35475024, 0.70709948, 0.05889793],
        [0.44692926, 0.90784004, 0.76926378, 0.46140052, 0.03515991,
         0.85895531, 0.7192956 , 0.71276866]]])

In [17]:
copyingAttention.Wk

array([[[0.36697658, 0.06369904, 0.11757953, 0.77782075, 0.49271612,
         0.26702898, 0.86802038, 0.69536612],
        [0.5710032 , 0.45574301, 0.30102574, 0.49330926, 0.15119503,
         0.57102484, 0.60463195, 0.33183582],
        [0.39867866, 0.2517794 , 0.65944202, 0.16160868, 0.15887035,
         0.08650789, 0.78103235, 0.84101309],
        [0.95848306, 0.92405462, 0.25148575, 0.43516406, 0.52300296,
         0.51775528, 0.75750532, 0.73836277],
        [0.03678485, 0.89462939, 0.45157634, 0.90545964, 0.41529144,
         0.25935511, 0.70386579, 0.34904258],
        [0.49665182, 0.81878398, 0.61515928, 0.21548799, 0.10016537,
         0.54760782, 0.35043095, 0.51290781],
        [0.62641349, 0.33198524, 0.04050908, 0.79537053, 0.1170476 ,
         0.35475024, 0.70709948, 0.05889793],
        [0.44692926, 0.90784004, 0.76926378, 0.46140052, 0.03515991,
         0.85895531, 0.7192956 , 0.71276866]]])

In [18]:
attention.commit_model()

In [19]:
import numpy as np

In [20]:
testInputForwardInfer = np.zeros((T, d_model))

In [21]:
attention.forward_infer(testInputForwardInfer)

array([[1.66876844, 1.28939353, 1.85628341, 2.12230823, 1.87947768,
        1.97325001, 2.16043114, 1.15516786],
       [1.66876844, 1.28939353, 1.85628341, 2.12230823, 1.87947768,
        1.97325001, 2.16043114, 1.15516786],
       [1.66876844, 1.28939353, 1.85628341, 2.12230823, 1.87947768,
        1.97325001, 2.16043114, 1.15516786],
       [1.66876844, 1.28939353, 1.85628341, 2.12230823, 1.87947768,
        1.97325001, 2.16043114, 1.15516786]])

### FFN

In [22]:
from transformer import FFN, FFN_init

In [24]:
ffn_init = FFN_init.randomInitial(
    d_model = d_model,
    expand_scale = 4
    )

In [25]:
ffn1 = FFN(ffn_init)

In [29]:
ffn1.W_expand

array([[[0.36697658, 0.06369904, 0.11757953, 0.77782075, 0.49271612,
         0.26702898, 0.86802038, 0.69536612, 0.5710032 , 0.45574301,
         0.30102574, 0.49330926, 0.15119503, 0.57102484, 0.60463195,
         0.33183582, 0.39867866, 0.2517794 , 0.65944202, 0.16160868,
         0.15887035, 0.08650789, 0.78103235, 0.84101309, 0.95848306,
         0.92405462, 0.25148575, 0.43516406, 0.52300296, 0.51775528,
         0.75750532, 0.73836277],
        [0.03678485, 0.89462939, 0.45157634, 0.90545964, 0.41529144,
         0.25935511, 0.70386579, 0.34904258, 0.49665182, 0.81878398,
         0.61515928, 0.21548799, 0.10016537, 0.54760782, 0.35043095,
         0.51290781, 0.62641349, 0.33198524, 0.04050908, 0.79537053,
         0.1170476 , 0.35475024, 0.70709948, 0.05889793, 0.44692926,
         0.90784004, 0.76926378, 0.46140052, 0.03515991, 0.85895531,
         0.7192956 , 0.71276866],
        [0.74360303, 0.24414772, 0.56787211, 0.64382124, 0.66236186,
         0.14312025, 0.63488072, 0.

In [31]:
forward = np.zeros((B, T, d_model))

rng = np.random.default_rng(40000)
backward = rng.random((B, T, d_model), dtype=np.float64)

In [32]:
ffn1.forward_train(forward)

array([[[24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742],
        [24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742],
        [24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742],
        [24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742]],

       [[24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742],
        [24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742],
        [24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742],
        [24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742]]])

In [34]:
ffn1.backward(backward)

array([[[  793.76198538,  1411.80782874, -5313.21299099,  -616.65939546,
          1579.89575306, -2704.55744255,  5096.66135098,  -247.69708915],
        [  723.39765915,  1366.97040886, -4697.02780828,  -609.8102598 ,
          1318.77970284, -2341.96457933,  4384.38874453,  -144.73386797],
        [  639.36096583,  1309.16172289, -5030.36194827,  -519.83756736,
          1479.01219828, -2554.41600305,  4895.02322488,  -217.94259319],
        [  680.89850654,  1191.72022855, -4956.95973839,  -475.24161289,
          1572.56229197, -2567.74714898,  4843.74325561,  -288.97578242]],

       [[  849.25267755,  1623.56914687, -6450.70341966,  -613.44543893,
          2023.33709374, -3326.54307451,  6275.26207602,  -380.72906108],
        [  649.89183846,  1476.72403533, -5457.23604992,  -465.57937635,
          1666.84190861, -2827.84081729,  5260.47168217,  -303.27322102],
        [  371.49849393,   766.37713338, -3112.33170828,  -263.97823591,
           949.85863065, -1612.92348309,  3

In [36]:
len(ffn1.d_W_expand_list)

3

In [37]:
ffn1.save_checkpoint()

FFN FFN1 has been save successfully @ d:\llm-scratch\checkpoint\FFN1.ffn.npz


In [39]:
copyffn1 = FFN.load_checkpoint("ffn1", activation_function=Relu, activation_function_backward=Relu_backward)

In [41]:
copyffn1.forward_train(forward)

array([[[24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742],
        [24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742],
        [24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742],
        [24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742]],

       [[24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742],
        [24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742],
        [24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742],
        [24.38549202, 30.75610036, 27.04156639, 31.66893688,
         31.8205891 , 29.22308292, 25.16599509, 27.53668742]]])