In [1]:
import numpy as np
from transformer import Attention, Attention_cache, Attention_init

In [2]:
B, T, C = 2, 4, 6

In [3]:
rng = np.random.default_rng(2000)

``` python
@dataclass
class Attention_init:
    gamma: npt.NDArray[np.float64] # (1, 1, C) or (C, )
    beta: npt.NDArray[np.float64]  # (1, 1, C) or (C, )

    attentionHead: int             # H

    Wk: npt.NDArray[np.float64]    # (C, C) when C is hidden param or d_model
    Wq: npt.NDArray[np.float64]    # (C, C)
    Wv: npt.NDArray[np.float64]    # (C, C)

    merge_heads_bias: npt.NDArray[np.float64] # (1, 1, C) recommend

```

In [4]:
attentionInit = Attention_init(
    gamma=  rng.random((1, 1, C), dtype = np.float64),
    beta= rng.random((1, 1, C), dtype=np.float64),
    attentionHead= 2,
    Wk=rng.random((1, C, C), np.float64),
    Wq = rng.random((1, C, C), np.float64),
    Wv = rng.random((1, C, C), np.float64),
    merge_heads_bias=rng.random((1, 1, C), np.float64),

)

In [5]:
attention = Attention(attentionInit, "attentiondemo")

In [6]:
def grad_check_transformer(forward, backward, eps=1e-6):
    rng = np.random.default_rng(1000)

    B, T, C = 2, 4, 6

    X = -rng.random((B, T, C), dtype=np.float64)
    G = -rng.random((B, T, C), dtype=np.float64) # upstream gradient

    # forward
    Y = forward(X)

    # analytical gradient
    dX = backward(G)

    # numerical gradient
    dX_num = np.zeros_like(X)
    it = np.nditer(X, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx = it.multi_index
        old = X[idx]

        X[idx] = old + eps
        Yp = forward(X)
        Lp = np.sum(Yp * G)

        X[idx] = old - eps
        Ym = forward(X)
        Lm = np.sum(Ym * G)

        X[idx] = old
        dX_num[idx] = (Lp - Lm) / (2 * eps)

        it.iternext()

    # compare

    max_abs = np.max(np.abs(dX - dX_num))
    rel = max_abs / (np.max(np.abs(dX) + np.abs(dX_num)) + 1e-22)


    print("max_abs_diff:", max_abs)
    print("relative_diff:", rel)

In [7]:
grad_check_transformer(forward=attention.forward_train, backward=attention.backward, eps=1e-6)

max_abs_diff: 4.636616424136264e-09
relative_diff: 2.67480814184169e-10


In [8]:
X = rng.random((B, T, C), dtype=np.float64)

In [9]:
attention.forward_train(X)

array([[[2.71597388, 1.73252146, 2.203777  , 2.72203599, 1.75673417,
         3.07373421],
        [2.64395868, 1.84011736, 2.29130665, 2.70965748, 1.64586452,
         3.01346946],
        [2.81911401, 2.29154911, 2.59839718, 2.70672895, 1.70087426,
         3.25348357],
        [2.65564606, 2.00655827, 2.35375729, 2.6648596 , 1.65775292,
         3.21420054]],

       [[2.29000886, 2.03391352, 2.12263565, 2.89122759, 1.92920488,
         2.77428405],
        [1.93699919, 1.72589908, 1.80466073, 2.77777043, 1.85191578,
         2.66252969],
        [2.20608967, 1.97848272, 2.12730529, 2.78160958, 1.77741753,
         2.80888682],
        [2.16643853, 1.79641102, 2.06787027, 2.66498002, 1.66682112,
         2.7459665 ]]])

In [10]:
attention.Q_split.shape

(2, 2, 4, 3)

In [11]:
attention.K_split.shape

(2, 2, 4, 3)

In [16]:
attention.causal_mask

array([[[[-0.e+00, -1.e+09, -1.e+09, -1.e+09],
         [-0.e+00, -0.e+00, -1.e+09, -1.e+09],
         [-0.e+00, -0.e+00, -0.e+00, -1.e+09],
         [-0.e+00, -0.e+00, -0.e+00, -0.e+00]]]])

In [12]:
attention.scores

array([[[[ 3.83496518e+00, -9.99999996e+08, -9.99999995e+08,
          -9.99999997e+08],
         [ 3.15911386e+00,  3.19127673e+00, -9.99999995e+08,
          -9.99999998e+08],
         [ 3.92299440e+00,  3.98181699e+00,  5.67189336e+00,
          -9.99999997e+08],
         [ 1.66152568e+00,  1.62701761e+00,  2.47209586e+00,
           1.32392322e+00]],

        [[ 5.31302940e+00, -9.99999995e+08, -9.99999995e+08,
          -9.99999999e+08],
         [ 4.86950489e+00,  4.25931395e+00, -9.99999995e+08,
          -9.99999999e+08],
         [ 6.81921798e+00,  5.99585957e+00,  6.66014132e+00,
          -9.99999998e+08],
         [ 3.57308366e+00,  3.18681124e+00,  3.57748393e+00,
           1.08859133e+00]]],


       [[[ 3.93651729e+00, -9.99999997e+08, -9.99999996e+08,
          -9.99999997e+08],
         [ 1.75224639e+00,  1.43867577e+00, -9.99999998e+08,
          -9.99999999e+08],
         [ 3.45922220e+00,  2.69459272e+00,  3.70621879e+00,
          -9.99999998e+08],
         [ 2.47

In [13]:
attention.output.shape

(2, 2, 4, 3)

In [14]:
attention.merge_heads(attention.output).shape

(2, 4, 6)

In [15]:
G = -rng.random((B, T, C), dtype=np.float64)