In [1]:
import numpy as np
from transformer import DataPipe, Attention, Attention_init
from llm_architect import gradCheckTransformer


In [2]:
rng = np.random.default_rng(1000)

In [3]:
B, T, C = 2, 4, 6

In [4]:
attention_init = Attention_init.randomInitial(1000, B, T, C)

In [5]:
attention1 = Attention(attention_init, name="attention1")

In [6]:
X = rng.random((B, T, C), dtype = np.float64)
G = rng.random((B, T, C), dtype = np.float64)

In [7]:
datapipe1 = DataPipe(attention1, "pipe1")

In [8]:
X

array([[[0.52138574, 0.60384185, 0.4709418 , 0.20324794, 0.52875903,
         0.19103628],
        [0.2815456 , 0.75368155, 0.55167178, 0.86372208, 0.80537222,
         0.24837266],
        [0.18985741, 0.98399558, 0.66999717, 0.28038283, 0.20391323,
         0.62506469],
        [0.65260432, 0.89880753, 0.97476378, 0.15393237, 0.69908928,
         0.44724145]],

       [[0.01751321, 0.29102491, 0.38123661, 0.32102791, 0.94254467,
         0.70266697],
        [0.13645032, 0.34320907, 0.8119946 , 0.148494  , 0.05932569,
         0.31441663],
        [0.42015645, 0.80801771, 0.00950759, 0.45408379, 0.55868699,
         0.00288863],
        [0.29775757, 0.05379911, 0.56766875, 0.94055815, 0.72427372,
         0.85637809]]])

In [9]:
datapipe1.forward(X)

array([[[2.92731031, 3.64970549, 2.82987184, 3.03292653, 2.78966686,
         2.37585661],
        [2.62748012, 3.76559931, 2.87639994, 3.69282288, 3.05419734,
         2.40204025],
        [2.57831517, 4.02108966, 3.01715936, 3.10804607, 2.45203883,
         2.77410199],
        [3.0705999 , 3.95000559, 3.34284252, 2.98443808, 2.95902098,
         2.62685162]],

       [[2.06686233, 3.07789028, 2.67295675, 2.76817822, 2.66990801,
         2.58773923],
        [2.43061012, 3.36021244, 3.17116117, 2.60836403, 1.7774915 ,
         2.2031919 ],
        [2.62197262, 3.73752966, 2.34369416, 2.90955258, 2.27655771,
         1.895684  ],
        [2.3653041 , 2.85860918, 2.86284572, 3.39856419, 2.45916779,
         2.74157538]]])

In [10]:
datapipe1.backward(G)

array([[[ 2.41285003,  2.22472937, -2.04523333,  0.90011486,
         -0.90000021,  1.55118337],
        [ 0.87155936,  0.0130008 ,  0.251672  ,  0.9039784 ,
          0.2907406 , -0.10037813],
        [ 0.72690891,  0.84910841,  0.61186865,  0.44967514,
          0.16050746,  0.60587398],
        [ 1.98935447,  1.99427983, -1.57962637,  0.29544729,
          0.41526847, -0.61259195]],

       [[ 0.32185471,  0.45552479, -0.55680801,  0.6032827 ,
          1.21986844,  0.21675636],
        [ 2.06889826,  3.5004103 ,  0.11545579, -1.18348155,
          0.41897137, -1.46227704],
        [ 4.41761999,  1.87243147,  2.8078601 , -4.52251238,
          0.28876851, -0.9056695 ],
        [ 1.05154022,  0.65393556, -0.03420616,  1.14178186,
          0.46557241,  0.2325902 ]]])

In [11]:
attention1.forward(X)
attention1.attentions
attention1.backward(G)

array([[[ 1.86853438,  1.84507868, -2.64965806,  0.16551087,
         -1.88840834,  0.65894246],
        [ 0.35191758, -0.19520604, -0.04726852,  0.06845299,
          0.1062341 , -0.28413012],
        [ 0.49188077,  0.19091983,  0.09513763, -0.37418209,
         -0.02915056, -0.37460558],
        [ 1.59650943,  1.54082655, -1.85391099, -0.02731921,
         -0.21214858, -1.0439572 ]],

       [[ 0.24525246,  0.35691117, -0.62328546, -0.1044688 ,
          0.3113764 , -0.18578577],
        [ 1.56583405,  3.25852471, -0.5832872 , -2.0691752 ,
         -0.51645184, -1.65544453],
        [ 3.45852444,  1.19743782,  2.06715991, -4.95657601,
         -0.33122775, -1.43531842],
        [ 0.39166759, -0.14403758, -0.16646665,  0.27549073,
         -0.24167614, -0.11497796]]])

In [12]:
gradCheckTransformer(datapipe1.forward, datapipe1.backward, eps=1e-6)

max_abs_diff: 7.659474166032965e-09
relative_diff: 7.308995839950999e-10
